name: "Build web"

on:
  push:
    branches:
      - feat/**
      - master

defaults:
  run:
    working-directory: ./web

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.17.0'

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
