name: "Build API"

on:
  push:
    branches:
      - main
      - feat/**
    paths:
      - "api/**"

jobs:
  api:
    name: "Build API"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup .NET"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: "Install dependencies"
        run: "dotnet restore api/src/Steno.Api/Steno.Api.csproj"

      - name: "Build"
        run: "dotnet build api/src/Steno.Api/Steno.Api.csproj --configuration Release --no-restore"