name: "Build web"

on:
  push:
    branches:
      - main
      - feat/**
    paths:
      - "web/**"

jobs:
  api:
    name: "Build web"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Install dependencies"
        run: |
          cd web
          npm install

      - name: "Build"
        run: | 
          cd web
          npm run build